language: java

jdk:
  - oraclejdk8
  - oraclejdk7

sudo: required


# Setup compiler
before_install:
- git clone https://github.com/maplesond/metaopt.git

install:
- cd metaopt
- ./install-linux.sh
- cd ..

